### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by codesynx** [VimukthiMK/EliteEstates#1]
Hey! How to deploy your web-app to vercel or netlify? Or how to run it with vs code?

**Comment by VimukthiMK** [comment]
Hi !
The project is still under development. So i will update the instructions with the deployment soon.

**Comment by VimukthiMK** [comment]
However, If you need to run it locally,
**Api directory -** 
1. Open terminal and Run "npm install"
2. Create .env file and define the environment variables
-  PORT = 8000
- DATABASE_URL
- JWT_SECRET_KEY
- CLIENT_URL= http://localhost:5173
3. run "npm start" command

**Client directory - (vite)**
1. Open terminal and Run "npm install"
2. Create .env file and define the environment variables For firebase storage.

- VITE_FIREBASE_API_KEY
- VITE_FIREBASE_AUTH_DOMAIN
- VITE_FIREBASE_PROJECT_ID
- VITE_FIREBASE_STORAGE_BUCKET
- VITE_FIREBASE_MESSAGING_SENDER_ID
- VITE_FIREBASE_APP_ID

3. run "npm run dev" command.
